classdef DataPreview < uix.HBox
    
    properties (Dependent)
        Data
        Info
    end
    
    properties (Access = protected) 
        
        info = {}
        ax
        counter
        prev_btn
        next_btn
        first_btn
        last_btn
        info_tbl
    end
    properties (Access = protected, SetObservable)
        data_
    end
    methods
        function self = DataPreview ( varargin )
            panel = uix.Panel(...
                'Parent', self, ...
                'Title', 'Preview' ...
            );
            vb = uix.VBox( ...
                'Parent', panel ...
            );
            self.ax = axes(...
                'Parent', uix.Panel(...
                    'BorderType', 'none', ...
                    'Parent', vb ...
                ) ...
            );
        
            hb = uix.HBox(...
                'Parent', vb ...
            );
            bbox1 = uix.HButtonBox( ...
                'Parent', hb, ...
                'ButtonSize', [32, 32] ...
            );
            self.counter = uix.Text( ...
                'Parent', hb, ...
                'VerticalAlignment', 'middle', ...
                'String', 'Counter' ...
            );
            bbox2 = uix.HButtonBox( ...
                'Parent', hb, ...
                'ButtonSize', [32, 32] ...    
            );
            self.next_btn = uicontrol(...
                'Parent', bbox2, ...
                'String', '>' ...
            );
            self.last_btn = uicontrol(...
                'Parent', bbox2, ...
                'String', '>>' ...
            );
            self.first_btn = uicontrol(...
                'Parent', bbox1, ...
                'String', '<<' ...
            );
            self.prev_btn = uicontrol(...
                'Parent', bbox1, ...
                'String', '<' ...
            );
            

            panel = uix.Panel(...
                'Parent', self, ...
                'Title', 'File details' ...
            );
            self.info_tbl = uitable(...
                'ColumnName', {'Description', 'Value'}, ...
                'Units', 'normalized', ...
                'ColumnWidth', {'auto', 'auto'}, ...
                'Parent', panel ...
            );
            self.info_tbl.Position(3) = 1;
            vb.Heights = [-1 64];    
        
            self.Widths = [-1 -1];
            self.Spacing = 10;
            self.Padding = 10;
            try
                uix.set( self, varargin{:} )
            catch e
                delete( self )
                e.throwAsCaller()
            end
            
%            addlistener(self, 'Data', 'PostSet', ...
%                @self.show_data);
        end
        
        function set.Data( self, data )
            minX = self.ax.Position(3);
            minY = self.ax.Position(4);
            
            ratioX = minX / size(data,2);
            ratioY = minY / size(data,1);
            
            self.data_ = imresize( data, min( [ratioX, ratioY] ));
            
            self.show_data();
        end
        
        function d = get.Data( self )
            d = self.data_;
        end
        
        function set.Info ( self, info )
            self.info_tbl.Data = info;
        end
        function info = get.Info( self )
            info = self.info_tbl.Data;
        end
    end
    methods (Access = protected)
        function redraw( self )
            redraw@uix.HBox(self); drawnow;
            % A maybe not so nice hack to set the column width to fill the
            % parent container. Might be possible in an easier way.
            w = self.info_tbl.Parent.InnerPosition(3);
            self.info_tbl.ColumnWidth = {w/2 w/2};
            drawnow;
            we = self.info_tbl.Extent(3);
            self.info_tbl.ColumnWidth = {(w-(we-w))/2 (w-(we-w))/2};
        end
        
        function show_data( self )
            imagesc(self.ax, self.data_);
            self.ax.DataAspectRatio=[1 1 1];
            colormap(hot);
        end
    end
end