function compose_gui_decon( self )
%COMPOSE_GUI_DECON Composes the GUI components for the deconvolution
%settings
panel = uix.Panel(...
    'Parent', self.gui.l_row3, ...
    'Title', 'Deconvolution' ...
);