function compose_gui_toolbar( self )
% COMPOSE_GUI_TOOLBAR Composes the toolbar

settings = { ...
    'Parent', self.gui.r_row1, ...
    'ButtonSize', [32 32], ...
    'HorizontalAlignment', 'left', ...
    'Spacing', 5 ...
};   
selection_bbox = uix.HButtonBox(settings{:});
zoom_bbox = uix.HButtonBox(settings{:});


zoom_original_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('zoom-original'), ...
    'TooltipString', 'Zoom to original size', ...
    'Parent', zoom_bbox ...
);
zoom_fit_best_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('zoom-fit-best'), ...
    'TooltipString', 'Fit best', ...
    'Parent', zoom_bbox ...
);

zoom_out_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('zoom-out'), ...
    'TooltipString', 'Zoom out', ...
    'Parent', zoom_bbox ...
);

zoom_in_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('zoom-in'), ...
    'TooltipString', 'Zoom in', ...
    'Parent', zoom_bbox ...
);

line_select_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('draw-line'), ...
    'TooltipString', 'Line profile', ...
    'Parent', selection_bbox ...
);

rect_select_btn = uicontrol( ...
    'CData', msrviewer.icons.get_breeze_icon('draw-rectangle'), ...
    'TooltipString', 'Rectangle selection', ...
    'Parent', selection_bbox ...
);

