function compose_gui_orig( self )
%COMPOSE_GUI_ORIG Composes the components of the original data preview


panel = uix.Panel(...
    'Parent', self.gui.l_row1, ...
    'Title', 'Original data' ...
);


self.gui.DataPreview = msrviewer.gui.DataPreview(...
    'Parent', panel, ...
    'PrevClick', {@self.change_preview, -1}, ...
    'NextClick', {@self.change_preview, +1}, ...
    'FirstClick', {@self.change_preview, 'first'}, ...
    'LastClick', {@self.change_preview, 'last'} ...
);

addToChannelBox = phutils.gui.LabeledButtonBox(...
    ...%'Parent', self.gui.DataPreview.ButtonBar, ...
    'ButtonSize', [32 32], ...
    'Label', 'Set as Channel' ...
);

uicontrol(...
    'Parent', addToChannelBox, ...
    'Callback', @(evt, src)self.set_channel(0), ...
    'CData', msrviewer.icons.get_breeze_icon('channel-add') ...
    ...%'String', '0' ...
);
uicontrol(...
    'Parent', addToChannelBox, ...
    'Callback', @(evt, src)self.set_channel(1), ...
    'CData', msrviewer.icons.get_breeze_icon('channel-add-one') ...
);
uicontrol(...
    'Parent', addToChannelBox, ...
    'Callback', @(evt, src)self.set_channel(2), ...    
    'CData', msrviewer.icons.get_breeze_icon('channel-add-two') ...
);
uicontrol(...
    'Parent', addToChannelBox, ...
    'Callback', @(evt, src)self.set_channel(3), ...    
    'CData', msrviewer.icons.get_breeze_icon('channel-add-three') ...
);

addToChannelBox.Parent = self.gui.DataPreview.ButtonBar;
