function compose_gui_psf( self )
% COMPOSE_GUI_PSF Sets up the GUI components for the PSF generation

panel = uix.Panel(...
    'Parent', self.gui.l_row2, ...
    'Title', 'PSF' ...
);

msrviewer.gui.PSFField(...
    'Parent', panel ...
    );